name: Keep Alive

on:
  schedule:
    - cron: '0 */3 * * *'  # Her 3 saatte bir çalışır

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -I https://tg-indirim.streamlit.app/
